# ===============================
# ????
# ===============================
spring.application.name=attendance-system

# ===============================
# ?????
# ===============================
server.port=8080

# ===============================
# ???????
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/springboot_course
spring.datasource.username=postgres
spring.datasource.password=123456

# ===============================
# JPA / Hibernate ??
# ===============================

# ???????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update

# ????? Hibernate ??? SQL
spring.jpa.show-sql=true

# ??? SQL?????
spring.jpa.properties.hibernate.format_sql=true

# ?? PostgreSQL ??
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ????????? SQL ??????????????
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace