-- 1. 用户表 (User)
CREATE TABLE "user"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    password    VARCHAR(100) NOT NULL,
    real_name   VARCHAR(50)  NOT NULL,
    role        VARCHAR(20)  NOT NULL DEFAULT 'TEACHER',
    create_time TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE "user" IS '用户表';
COMMENT ON COLUMN "user".role IS '角色：TEACHER/ADMIN';

-- 2. 课程表 (Course)
CREATE TABLE course
(
    course_id      VARCHAR(20) PRIMARY KEY,
    course_name    VARCHAR(100) NOT NULL,
    class_name     VARCHAR(50)  NOT NULL,
    teacher_id     BIGINT       NOT NULL,
    classroom_name VARCHAR(50),
    rows           SMALLINT, -- Postgres用SMALLINT代替TINYINT
    cols           SMALLINT,
    exclude_seats  TEXT,     -- 存储不可坐座位
    weekday        SMALLINT,
    start_week     INT,
    end_week       INT,
    create_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_teacher FOREIGN KEY (teacher_id) REFERENCES "user" (id)
);
COMMENT ON TABLE course IS '课程表';

-- 3. 选课表 (Course Selection)
CREATE TABLE course_selection
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   VARCHAR(20) NOT NULL,
    student_name VARCHAR(50) NOT NULL,
    gender       CHAR(2),
    course_id    VARCHAR(20) NOT NULL,
    select_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_course_selection FOREIGN KEY (course_id) REFERENCES course (course_id)
);

-- 4. 考勤记录表 (Attendance)
CREATE TABLE attendance
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    VARCHAR(20) NOT NULL,
    student_name  VARCHAR(50) NOT NULL,
    course_id     VARCHAR(20) NOT NULL,
    check_in_time TIMESTAMP   NOT NULL,
    seat_row      SMALLINT,
    seat_col      SMALLINT,
    status        VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    ip            VARCHAR(45), -- 兼容IPv6
    create_time   TIMESTAMP            DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attendance_course FOREIGN KEY (course_id) REFERENCES course (course_id)
);
-- 创建索引（提高查询效率）
CREATE INDEX idx_attendance_course ON attendance (course_id);
CREATE INDEX idx_attendance_student ON attendance (student_id);